apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: msevcik/ambulance-ufe
  newName: msevcik/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20260211.1230 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
